### ISSUE TITLE
🐛 Adding Users with same email address

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#1072]
## Describe the bug
I shouldn't be able to add multiple users with the same email address. Currently it just makes the last one you add (with the same address) a program user.

## Steps To Reproduce

Steps to reproduce the behaviour:
1. Go to add users modal for a program
2. In that same modal, add multiple users with different names, different roles, but same email address
3. Click Add users
4. see success toast say 4 users were added, but only the last one you added was:
![Screen Shot 2020-02-04 at 11 02 14 AM](https://user-images.githubusercontent.com/18424138/73762364-1be8af80-473e-11ea-8bbe-f73cd6db3efa.png)

## Expected behaviour
(Change in design from the comments below)
- program admin fills out the users they want to add
- when the admin presses "add users" button, and if email addresses have already been used in this form or within the already existing program members, an error shows in the user box(es) that has the error "The email address for this user has already been used."
- validation happens on "add users" button click, the admin has to fix the error in order to go further and add any of the other users.

<img width="819" alt="Screen Shot 2020-02-28 at 3 17 28 PM" src="https://user-images.githubusercontent.com/18424138/75584318-7b846300-5a3d-11ea-8b63-2af032c08994.png">

**Comment by P-Saha** [comment]
@kcullion Adding the notification where requested under the field is difficult, as the field validations are self-contained, i.e. they rely only on what is in the field. Since the same email used requires knowledge of other emails outside of the field/outside of it's scope, and requires this information dynamically (as more fields get added), it is a bit more difficult to have that notification where requested (within the scope of the field). Would it be possible to put that notification above the "add another" button rather than under the field? Or some other design?

**Comment by kcullion** [comment]
@P-Saha that is where all of the notifications show up (like name is required, email is required...) so I'm not sure I understand why this one can't show there

**Comment by kcullion** [comment]
@P-Saha can you esplain to me when the error would show up in the modal...like is it when the user presses "add users" or when they put an already used email address in the email field and then mouse away from that field?

**Comment by kcullion** [comment]
Maybe we make the validation happen on the "add users" button - then an error could show up at the top of the modal. But would you be able to highlight the fields that have the error with the red border?

**Comment by P-Saha** [comment]
I had the assumption that it was in the modal and mousing away, which is difficult. If it is when the user presses "add users", that is easier to do and fixes the issue of the notification being under the field.

The current notifications of "email is required", "email is invalid", etc. all do not use any outside information, it only depends on the text within the field. The email being the same as a different email requires information that is outside of the scope of the field itself, i.e. knowledge of the other fields. Right now the field error notifications are directly connected to the text inside the field. That is the big difference between the errors which makes it hard.

**Comment by P-Saha** [comment]
The highlighting of the boxes is what is giving me problems. I currently have it so that when an email is duplicated you cannot add a user and "add another" button is disabled, but it gives no indication as to why. I can have a notification appear above all of the users saying you cannot add duplicate emails, but having the notification on the individual user is more difficult.

**Comment by rosibaj** [comment]
tested on prod deploy - cannot add the same email address in modal, or an email address that has already been added.
