### ISSUE TITLE
Data Hookup - Gateway to Top Dashboard Stats 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1240]
The stats on the top of the dashboard can now be connected to the gateway
Using the new `donorSummary` schema, hook up the dashboard summary card to the platform api

QUERY:
```
query{

  programDonorSummaryStats (programId: "RAWR-CA"){
    registeredDonorsCount
    percentageCoreClinical
    percentageTumorAndNormal
    donorsProcessingMolecularDataCount
    filesToQcCount
    donorsWithReleasedFilesCount
    allFilesCount
     }
}
```
![image](https://user-images.githubusercontent.com/15824252/77203854-dd2d6f80-6ac7-11ea-992f-c8c2946de260.png)

**Comment by wajiha-oicr** [comment]
from @hlminh2000 's program MINH-CA in dev

- maybe we could benefit from passing the numbers into a rounding function before displaying them?
- the number of committed donors was 2, but Minh went really above and beyond and registered 2501. since those two numbers are not equal to one another, it's showing up as an orange bar. but I figure if the percentage is over 100% that probably also qualifies as a reason to show it as a green bar.

**Comment by rosibaj** [comment]
@P-Saha  a few comments: 
1. For the dashboard numbers, lets remove the decimal entirely and round to the nearest whole number:
![image](https://user-images.githubusercontent.com/15824252/78606241-fbff6600-782a-11ea-9e3d-47dc6a105dc3.png)
2.  As @wajiha-oicr suggested, if the value is 100% or > 100%, the bar should be green, not orange.

**Comment by rosibaj** [comment]
@hlminh2000 @P-Saha For this ticket, i think the connection to % tumor normal based on the graphql provided in the ticket is correct. 

Why does this field already have value in elasticsearch though?  When did we add a calulation for that?
