### ISSUE TITLE
BUG: Clearing a file clears the errors in another tab

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/platform-ui#1520]
Steps to reproduce:
1- upload  a file with upload errors like specimen
2- upload another good file of another type like treatment
3- clear the good file 
notice the error in the tab with error is cleared too.

**Comment by wajiha-oicr** [comment]
@blabadi @rosibaj I'm not too sure if this is a UI bug? From my testingI noticed that clearing a good file doesn't simply clear the upload **errors** of a file, but rather clears out the entire file. 

I guess my question is, is this not intended behaviour? I believe this is because after clearing a good file, it triggers a refetch of the active clinical submission, which naturally would not return the uploaded error files because they would not have been included in the active clinical submission?

**Comment by blabadi** [comment]
the problem is that if I clear treatment tab it shouldn't clear specimen tab

**Comment by wajiha-oicr** [comment]
but I believe the UI is just reflecting the state of the active clinical submission. 'clear' triggers a re-fetch of the clinical submission so files with errors don't show up as a result.

 i.e. same thing happens, for example: you can upload a file with errors, refresh the page, and that tab is cleared.

**Comment by blabadi** [comment]
cool no problem then I guess we have to live with this behavior
