### ISSUE TITLE
Feature Request: Integrate Clinical Warnings into UI

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1728]
UI for discussion: 
![image](https://user-images.githubusercontent.com/15824252/82930000-a0ac4300-9f52-11ea-9c58-56c79038953f.png)

Zeplin link: https://zpl.io/beEQkqW 

Clinical Ticket for Reference: #435

**Comment by blabadi** [comment]
the specs of the warning notification are hard to generalize, and do not fit the current way the components are designed, what I mean is the warning title and message will not fit if we decide to add more warnings in the same table (same way we do with errors) we show 1 table for all kinds of errors, same should apply for warnings

![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/69af8861-5d6b-48ff-9a86-388a06956ad8)

**Comment by blabadi** [comment]
updated image of the warning table:
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/118f3c19-647b-41e7-9599-f0a18a896081)

**Comment by rosibaj** [comment]
tested on QA: 

![image](https://user-images.githubusercontent.com/15824252/91312225-fe367280-e781-11ea-8583-bf230b1d4103.png)
 

Worked correctly warning me i was chaning data, and also was able to sign off.  uploading the same files did not result in a warning after. 

@blabadi Thanks!!! lgtm!

**Comment by kcullion** [comment]
@blabadi I tested this in staging by:
1. download all clinical data from DASH-CA donor table on dashboard
2. took the treatment file and changed the treatment type for donor: DASH-2 from "Radiation therapy" to "Chemotherapy" for treatment id: dashtr2-2
3. uploaded the new treatment entry along with a chemo file with two drugs listed
4. got the correct warning that my radiation therapy treatment info will be lost
5. signed off on that submission and see the warning with the note that my submission is marked for dcc approval
6. Bashar approved my submission
7. donor dashboard table update correctly with DASH-2 at the top of the list as most recently updated. When I download the clinical data from this table, DASH-2 entries are now updated to chemotherapy instead of radiation.
