### ISSUE TITLE
Feature Request: Connect Filters to Dashboard - Donor 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1983]
- [x]  Connect the Donor Filter (https://github.com/icgc-argo/platform-api/issues/415) 
- [x]  Add the filter to the UI table 
**Donor ID Filter** Zeplin mockup: https://zpl.io/bzdpqLG

Reference for storybook for the UI component library: https://argo-ui-storybook.netlify.app/

https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=Program+Dashboard+Page+Specs#ProgramDashboardPageSpecs-4.1TableDataFields,Filters,&DataSources

As discussed on Slack...The following outlines the general filter behaviour for the columns (for testing too)

- [x] The filter icon when hovering changes from grey to the blue. Nice to have: a tooltip that says "Filter by column name" when hovering over the filter icon
- [x] The user clicks on the filter icon to open the filter options. It closes when they click on that filter icon OR clicks on another filter icon (two filters would not be open at the same time) OR clicks anywhere else on the screen besides the filter option dropdown
- [x] Clicking anywhere else on the table header cell will sort the column as it's working now
- [x] When the filter is open, the active state would be the whole header cell gets shaded grey and the filter icon is blue.

**Comment by mistryrn** [comment]
Noticed a few oddities on some edge cases while testing, discussed the following fixes with @kcullion :

- [] to indicate that a filter is applied on a column when the panel is closed, the filter icon will stay blue when it is active (even when closed)
- [] a `min-height` will be applied to tables with filters, so that the filter panel can stay visible without scrolling when the height of remaining rows is less than the filter panel height
- [] when there is no data in the table, don't change the opacity of the header row so that users still know they can interact with the filters
- [] fix donor/file count not updating when filters are applied

**Comment by rosibaj** [comment]
last bullet point covered by
- https://github.com/icgc-argo/platform-api/issues/451
- https://github.com/icgc-argo/platform-api/issues/452
- https://github.com/icgc-argo/platform-api/issues/453

**Comment by rosibaj** [comment]
confirmed in production release sept 02, 2021
