### ISSUE TITLE
🐛 Regular failures to load file repository data correctly 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1985]
## Describe the bug
When using the file repository, intermittently it does not show the correct data based on my query. 
### Example 1

![image](https://user-images.githubusercontent.com/15824252/124190646-a0a13f80-da90-11eb-855f-cd800a156662.png)

### Example 2
![image](https://user-images.githubusercontent.com/15824252/124190848-eeb64300-da90-11eb-91b3-0b9e397f43ae.png)

## Expected behaviour
The file repository should always load the expected dataset base don my logged in user.

**Comment by joneubank** [comment]
`_buildManifest.js` issue:

This file is loaded from the UI server to help with NextJS navigation stuff. When Next builds the site, it generates an ID. That ID is part of the path to this manifest file. This error was due to a situation where some of the pods running in one environment were using a different build ID than the others, so you could load the page and then fail to fetch the Manifest file. This breaks everything on the site. This should not happen since the build step happens during Docker creation, not on run. Therefore, this should not happen unless the deployment uses different images across pods.

Redeploying the environment seems to have fixed this issue, we should monitor if it comes up again and if so we can force a static build ID: https://nextjs.org/docs/api-reference/next.config.js/configuring-the-build-id
