### ISSUE TITLE
🐛 Sometimes login not working on QA

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#1986]
- logged in with fakerosifortesting@gmail.com
- login loaded forever without letting me in
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/9a38b418-b1ad-4733-b6ae-7fa0ca0c79b7)
- on refresh i saw this issue: 
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/de551fb5-73e1-48c3-9997-f7f1fe6373a7)
- had to attempt ligin 2 more times with this account before it worked,

## Expected behaviour
Login should work the first time as expected,

**Comment by joneubank** [comment]
_buildManifest.js issue:

This file is loaded from the UI server to help with NextJS navigation stuff. When Next builds the site, it generates an ID. That ID is part of the path to this manifest file. This error was due to a situation where some of the pods running in one environment were using a different build ID than the others, so you could load the page and then fail to fetch the Manifest file. This breaks everything on the site. This should not happen since the build step happens during Docker creation, not on run. Therefore, this should not happen unless the deployment uses different images across pods.

Redeploying the environment seems to have fixed this issue, we should monitor if it comes up again and if so we can force a static build ID: https://nextjs.org/docs/api-reference/next.config.js/configuring-the-build-id
