### ISSUE TITLE
Allow platform-ui to consume the newly published uikit npm-package

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/platform-ui#2095]
platform-ui
    - needs to consume the published uikit npm-package and not the local code
    - Includes testing to ensure everything is working correctly. This is manual.

- Testing
  - platform-ui was the only project locally, so will test this explicitly.

**Comment by akachru-github** [comment]
@ciaranschutte , does this change apply for any project that will reference the uikit? DACO, HCMI etc?

**Comment by ciaranschutte** [comment]
There are some `uikit` things in `platform-ui` that are not in the `uikit` repo since this ticket was started. This splintering should be fixed before we depend on `uikit` fully.

Local dev is not perfect. Requires a local publish of a package just to see changes. Some time to find an efficient workflow would be beneficial

**Comment by ciaranschutte** [comment]
Issues still needing resolution.
- svg needs to be inlined at Babel stage of uikit build because parent projects have `svg` loading just for their own files and not dependencies eg. platform-ui uses `next-images` but this doesn't load svg for dependencies
- node versions after 14 require more specific versioning. this seems to work fine using the `--legacy-peer-deps` flag but some more testing is needed
- uikit uses its own version of Emotion which breaks the `theme` object. currently investigating using peerDependencies and webpack externals

**Comment by ciaranschutte** [comment]
theme is empty for imported components on Next SSR.
Upgrading to Emotion 11 does not help.

**Comment by ciaranschutte** [comment]
in progress:
- imports and typings updated
- resolving local dev duplicate react version issue

**Comment by ciaranschutte** [comment]
everything appears to be working great as far as integration goes.
holding off on the merge until I fix storybook so that is usable.

**Comment by Buwujiu** [comment]
@ciaranschutte will check if everything still good before closing.

**Comment by ciaranschutte** [comment]
double checked. all ok right now
