### ISSUE TITLE
🐛 Broken file entity page for associate member access file

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2149]
## Describe the bug
When logged in as DCC admin, and I filter for "Associate member access' in the file repository, the first file in the link leads to a broken page:
https://platform-ui.qa.argo.cancercollaboratory.org/file/00174996-9aab-5042-be32-dc27c5c240b0

## Expected behaviour
I should have access to see this page, wonder if there are any others like this? 

![image](https://user-images.githubusercontent.com/18424138/146974582-c2fc550a-f380-4aee-b310-9391727046c2.png)

**Comment by joneubank** [comment]
The cause is properties of the file document in elasticsearch that we expect to be a string are stored as an array of strings, when Arranger reads these values and tries to convert the array into a string for the response it throws an error.

The propery in question is `analysis.variant_class`, and it looks like `analysis.variant_type` also has documents with the value stored as an array instead of a string.

We found no examples of this broken data in staging/prod, so current theory is that this is just bad data provided to QA environment.

To fix, we likely need to update the values stored for these analyses in SONG and then re-index into ES file-centric indices.

**Comment by joneubank** [comment]
Even though the `variant_class` property has an error, GQL still returns all other values! we should be able to still render the page with all the rest of the data showing.

Let's update the UI to still render this page when possible. @kcullion should we add some kind of element shown that says "there were such and such error" on the page since we know at least SOMETHING went wrong...

**Comment by kcullion** [comment]
@joneubank so are you saying this won't happen in production? or it could?

 wondering if `analysis.variant_class` and `analysis.variant_type` are shown on the file entity page?

**Comment by joneubank** [comment]
it could happen in prod in theory but looks like its not happening there atm and is unlike to start.
i dont know where it is shown, if it isnt then we can remove it from the query.

**Comment by lindaxiang** [comment]
@kcullion the file with object_id `00174996-9aab-5042-be32-dc27c5c240b0` is from an analysis which was published long time ago. Since then, the SONG schema had a lot of major changes:
- current schema does NOT have `variant_type`
- `variant_class` is also changed to `string` instead of `array` 
So we should not have this kind of broken data in staging/prod.

**Comment by kcullion** [comment]
amazing, thanks for checking @lindaxiang !
@joneubank what do you suggest to do for now - just ignore this broken page because it won't happen again?

**Comment by demariadaniel** [comment]
I'm looking into ways the UI can handle this --- all the file data is there, so potentially we could render a badge or warning to notify there was an error with the file data, rather than just navigating to an error page

Once I have the basic code in place (should be this afternoon) we could touch base about the preferred UX

**Comment by demariadaniel** [comment]
@joneubank was also suggesting code at the API / Arranger level which could help us handle future issues

**Comment by kcullion** [comment]
I can't seem to find anymore broken pages, well done @demariadaniel !
That said, I just filtered on some of the values we knew to be issues (like EUCANCAN-BE), is there a way to test if any 404s still exist?
Although, I do trust that you made it so none will occur based on those problematic fields

**Comment by kcullion** [comment]
I can't find any broken entity pages on staging
