### ISSUE TITLE
Donor Entity: styling updates - fixing spacing

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#2273]
The following were the last few things to fix on the donor entity page styling. Dan's laptop monitor is too small to recreate some of these bugs. We may need someone else to look at them.

Continuation of these: https://github.com/icgc-argo/platform-ui/issues/2242

- [x] I still see the spacing between tables increase when refreshing the page. The clinical timeline card also sometimes has padding-right and sometimes doesn't on refresh. Let me know if you want to hop on a call to see what I mean.
![image](https://user-images.githubusercontent.com/18424138/159790659-201a349f-fa77-46e6-a0ae-7ae35682c6d1.png)

- [x] perhaps related to this item above - there's a grey background with part of the clinical timeline background happening 
![image](https://user-images.githubusercontent.com/18424138/159791080-8467fa1d-899a-4681-9a77-f2e1358a6d80.png)

- [x] Can you make it always show all of the data tables in each timeline tab? Specifically this specimen tab. I didn't notice there was a scrollbar here so I missed the bottom tables
![image](https://user-images.githubusercontent.com/18424138/159791257-21152d29-e380-4b8b-b3b6-04e0b541de4e.png)

**Comment by daniel-cy-lu** [comment]
The second checkbox is related to the right padding, and the bug couldn't be duplicated. Tested the page on a monitor and played with more viewport, bug is not being able to duplicated.

**Comment by Buwujiu** [comment]
Discuss point 3 with @patrickdsantos.

**Comment by daniel-cy-lu** [comment]
@Buwujiu Update: First requirement in this ticket is due to table data is changing when this page gets refreshed. As the result, the tables get resized and seem like the gaps are changing in size as well. The other two requirements cannot be replicated. This has been tested in localhost, DEV and QA. This is the grey area that Kim mentioned as well as the bottom table in specimen tab is always showing even after adjusting browser sizes.

**Comment by Buwujiu** [comment]
Based on the investigation results, no code is required, will close ticket.
