### ISSUE TITLE
Upgrade Next 11 to 12

### ISSUE THREAD

**Issue by samrichca** [icgc-argo/platform-ui#2310]
Upgrade Next 11 to 12

**Comment by b-f-chan** [comment]
Required for this epic, will resolve many high alert vulnerabilities and keep us on latest version

**Comment by b-f-chan** [comment]
Turns out we do have issues and this won't be smooth, when we get images from UIkit, we use 2 libraries that are NOT updated for Next 12.  One will never get updated (stagnant since 2018), so best thing to do is pass down an optional image component from whatever is using UIKit, then UIKit will be able to render the images properly.  Other option is use an SVG inline loader?  UIKit needs to be more extensible.

Consensus then = Inline the SVGs because it blocks 12.2, then when we get to Q4 updates for ARGO, adopt these changes from UIKit)

**Comment by samrichca** [comment]
https://github.com/icgc-argo/platform-ui/pull/2364
