### ISSUE TITLE
🐛 Error Counting Inconsistency on Submitted Data Page

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2385]
## Describe the bug

1. `Affected Records` should show the number of rows that are highlighted in the table. 
In ticket https://github.com/icgc-argo/platform-ui/issues/2350, One of the comments is: 
`As discussed in demo, let's change this header to # Affected Records, since it's not always unique donors`

However right now, some `Affected Records` are counting the donors, and some are counting the rows.
Example: https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?tab=treatment

![Screen Shot 2022-09-07 at 5 10 43 PM](https://user-images.githubusercontent.com/8744047/188981479-49032c4b-9c1a-4e25-9414-05db4b19755a.png)

2. On the submitted data page, there are a few cases where the errors in the table do not match the clinical API.

Example 1:
https://platform-ui.qa.argo.cancercollaboratory.org/submission/program/HNAHAL-CA/clinical-data?tab=treatment
On the ui, donor DO259184 has 5 errors for `line_of_treatment`, but the error report table says 3 `Affed
In the clinical API: {{clinicalUrl}}/clinical/program/HNAHAL-CA/clinical-errors?donorIds=259184, if search error by `line_of_treatment`, there are only 2 errors for donor DO259184. 

Why are we seeing these inconsistencies? 

![Screen Shot 2022-09-07 at 4 58 36 PM](https://user-images.githubusercontent.com/8744047/188978359-06c528e4-967d-46eb-8140-f261aa81812a.png)

## Expected behaviour
- the error counts in `Affected Records` should match the number of highlighted cells of `line_of_treatment` in the data table.
- these numbers should match the number of errors reported by clinical API. @Buwujiu to check with Dan to verify which API, clinical-errors api?

**Comment by demariadaniel** [comment]
The Errors returned by the Migration Service do not give enough information to determine which specific records are affected 100% of the time

For now all records with the same DonorId + FieldName as the Error object are counted and highlighted
Missing Fields + 'Invalid By Script' errors w/ missing fields are covered by this PR

**Comment by hknahal** [comment]
The dictionary includes a validation check as follows:
![line_of_treatment_validation (1)](https://user-images.githubusercontent.com/4992044/196813239-e4012f86-524c-4011-8fc8-1631904d1be8.jpg)
- if `is_primary_treatment` = `Yes`, then `line_of_treatment` should be empty (should not be submitted)
- if `is_primary_treatment` = `No`, then `line_of_treatment` should be a value greater than 1 (since it is not the primary treatment), or left empty (since it is an 'Extended' (optional) field).

However, the 'Submitted Data' section shows rows as errors, but they are not actually errors:

![line_of_treatment](https://user-images.githubusercontent.com/4992044/196804149-ec2ca21f-cb4a-443a-8292-fecd6cb7925e.png)

**Comment by Buwujiu** [comment]
The fix will be done in overture-stack/lectern#164.
Moving to awaiting release.
