### ISSUE TITLE
🐛 Core Completion Quick filters not working as expected

### ISSUE THREAD

**Issue by sifavahora** [icgc-argo/platform-ui#2418]
![image](https://user-images.githubusercontent.com/30519419/196837123-46ac3f17-707e-4f2e-a7f4-d752d069952a.png)

**Comment by demariadaniel** [comment]
So the issue here is our completionStats have `coreCompletionPercentage` of `1` (i.e. 100%) and are therefore 'Complete' but have `coreCompletion` fields which are `null`

So this is actually an accurate representation of the data

Does it make sense to update the definition for the `Complete` filter to be `coreCompletionPercentage === 1` & `all completionFields === 1` ?

![Screen Shot 2022-11-11 at 2.09.51 PM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/03398d2e-66d4-4b30-9811-a8ef10157ec5)

**Comment by demariadaniel** [comment]
Another observation, we have 8 coreCompletion fields, but only 6 of them are displayed on our UI.

There are cases where the 6 columns in our UI are complete, giving the impression that the data is clinically complete. However, the remaining 2 coreCompletionFields are not complete, and the coreCompletionPercentage is 83.33%. So when you filter on 'Complete', these records are filtered out. This could lead to a confusing user experience.

![Screen Shot 2022-11-11 at 2.09.51 PM.png](https://images.zenhubusercontent.com/619d338b44e7d7d8ae43f6df/e081c0d3-ace3-467f-a72f-8f47de3a0dba)

**Comment by demariadaniel** [comment]
@Buwujiu OK the real CoreCompletion issue is that we are filtering all Samples which include 'RNA' in `sample_type`

`specimens` coreCompletion is technically complete, but because we are not including RNA samples, we mark `coreCompletion -> normalSpecimens/tumourSpecimens` empty

**Comment by Buwujiu** [comment]
@demariadaniel as discussed with Linda, the solution to this is to change the clinical API core completion calculation, so that:
For the Normal and Tumour specimen:
Only need to count DNA specimen (so use sample_type field to see if it matches these values: Amplified DNA, ctDNA, Other DNA enrichments, Total DNA). 
Don't even need to show the RNA specimen counts as they are optional and not counted towards clinical completeness 

The change can be done in a separate ticket.

**Comment by Buwujiu** [comment]
Closing since the fix will be done separately.

**Comment by Buwujiu** [comment]
No PR for this ticket, solution will be done separately. closing issue.
