### ISSUE TITLE
Bug - Wrong Fields Appended to Donor Table

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-ui#2743]
## Steps to reproduce
1. Go to https://platform.staging.icgc-argo.org/submission/program/MUTO-INTL/clinical-data?donorId=&tab=donor
2. These fields are from Comorbidity table, but are showing in Donor table
<img width="1694" alt="Screenshot 2023-11-16 at 1 40 58 PM" src="https://github.com/icgc-argo/platform-ui/assets/8744047/75aaeb3b-6c71-462c-8200-6ab754cf3e3a">

**Comment by demariadaniel** [comment]
The source of the issue is the Donor records, not the submitted data code.
The table is accurate and the Donors have these fields in clinical info.
They were last valid in Dictionary 1.5. There are 4903 Donors affected this way in Prod.

The solution is we need to resubmit the data for these Donors, with comorbidity fields submitted as a comorbidity record.

Before we do anything in Staging/Prod, we should test in QA.
So we'll need to submit an updated valid donor record w/ comorbidity data, which should resolve the issue
Examples of the same issue are found in HNAHAL-CA QA

**Comment by edsu7** [comment]
data correction ticket started in:
https://github.com/icgc-argo/workflow-roadmap/issues/397
