### ISSUE TITLE
For any Card: min-height:300px

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-ui#591]
Program list card should be given a min-height:300px; so that it doesn’t look awkward and short while loading data

If no min-height is defined, min-height for any card should be 300px;
(eg program list card, user list card)

If a min-height is defined, like on the profile & tokens page, use that

**Comment by d8660091** [comment]
I suggest to do ad-hoc fix, instead of changing all cards. Many places will look strange after set min-height to 300px, including following:
![image.png](https://images.zenhubusercontent.com/5c8bd6685d1ca246a7c4850a/e3855111-2418-4080-b7eb-1a6de054605e)

![image.png](https://images.zenhubusercontent.com/5c8bd6685d1ca246a7c4850a/5f75b05d-27ff-49f8-94c7-36b1eb12e923)

![image.png](https://images.zenhubusercontent.com/5c8bd6685d1ca246a7c4850a/3790ed24-b66e-4465-8fa1-016d5731aa31)

**Comment by rosibaj** [comment]
@kcullion Do you want to define the min-heghts here or do as @d8660091 has suggested?

**Comment by kcullion** [comment]
@rosibaj @d8660091 I guess it's sort of the same work either way. Let's just go back to ad hoc fixes if that's easier right now

**Comment by d8660091** [comment]
The work to do is the same physically, counting by word changes. But it's psychological harder for programer to reset the css property back to default as `min-height: auto`. It's much more comfortable to set `min-height: 300px`. If we change the default behavior of a html component. It could easily add more issues as the hidden overflow dropdown menu of the page size selection does.

**Comment by kcullion** [comment]
@rosibaj , we will go back to what it was like where we change the min-height on a case by case basis as @d8660091 suggests

**Comment by d8660091** [comment]
@kcullion @rosibaj I'll just change the min-height of the program-list container. Please let me know if there are any other cards need to be adjusted

**Comment by kcullion** [comment]
thanks @d8660091 
I think we can make the program user list have the same min-height as the program list container

**Comment by rosibaj** [comment]
sounds good guys!!
