### ISSUE TITLE
🐛 Redirect is not working

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#678]
## Describe the bug
Redirect is not working correctly: 
![image](https://user-images.githubusercontent.com/15824252/65777716-92cbc700-e112-11e9-8c76-8f87df557308.png)

## Steps To Reproduce
Its not 100% consistent - usually happens on 1st login of the day.

## Expected behaviour
- [ ] If I login form the homepage it redirects me based on my role
- [ ] if i go to a controlled url and am not logged in, then i get directed to the login page.  once i login, i directed to page i tried to visit before. 

## Potential Solutions
- [ ] Integrate the latest ego version that include redirect URI (https://github.com/overture-stack/ego/releases/tag/2.9.2) 
- [ ] Change the portal ui to respond to redirects

**Comment by kcullion** [comment]
@rosibaj I'm getting this too when I login (as my dcc admin user from chrome)

**Comment by ciaranschutte** [comment]
@hlminh2000 @andricDu 
## Problem
User is not redirected based on permissions.
e.g. a non DCC user has no permission for `/submission/program`, they should be redirected to `user`, instead they are still redirected to `/submission/program` with a 401 banner.
Not sure why this specific ended up back at root page.

## Steps to reproduce
1. from root page navigate to `${root}/submission/program`, url should change but log in still needed. this sets `REDIRECT` in local storage to `/submission/program` 
2. click login
3. login as non DCC member

## 
`logged-in.tsx` is our auth callback page.
``` javascript
 if (token) {
        if (currentRedirect) { 
          localStorage.removeItem(LOCAL_STORAGE_REDIRECT_KEY);
          Router.replace(currentRedirect);
        } else {
          Router.replace(getDefaultRedirectPathForUser(token));
        }
      }
```
Adding additional logic to check if user has permission is not scaleable because we'd have to add conditions for every page
i.e ``` if(currentRedirect && hasPermissionForPage)```

**Comment by rosibaj** [comment]
Closing this issue as a duplicate
