### ISSUE TITLE
Selenium testing for Registration 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/platform-ui#744]
- need sample files for testing
- central place for test sample_registration files
- happy path
- invalid schema
- invalid file name
- data conflict

**Comment by joneubank** [comment]
So many issues discovered here... Can't do file upload in browser, so have to generate the data and post directly to gateway. this means in registration we can't test the error case (since invalid registration data is not stored and we cant use the upload file interface). We are able to test all the success cases though, including empty state, upload, clear, and register (commit).

**Comment by rosibaj** [comment]
@joneubank 👍  re: issues - perhaps that case just cannot be covered by selenium tests.  We don't really have another framework set up right now that can handle that right?
